# Generated by Django 4.1 on 2022-10-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
