# Generated by Django 4.1 on 2022-10-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0004_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
